### ISSUE TITLE
kiln-tuner cooling state

### ISSUE THREAD

**Issue by felixn-unity** [jbruce12000/kiln-controller#48] opened 2021-10-24 17:07 UTC
Hi

When running the kiln-tuner.py should it not run until target tempature and ALL the way down to the start tempature?

Or does it just need to run until target tempature is met?

Thanks
Felix

**Comment by adq** [comment] 2021-10-30 15:33
Hi, I've just run a test on my kiln, and verified that the master branch definitely looks good.

The test worked as expected for me:
![adq-kiln](https://user-images.githubusercontent.com/322473/139539363-a8006217-73ec-4835-98f7-5e44a73fcef6.png)

The code basically turns the heater on, waits for the temperature to reach 400 (it'll overshoot). It then turns the heater off and waits for the temperature to decay back to 400 again.

The target is either 400C or 400F - it depends what scale you have configured in config.py (I run mine in C). I guess 400F is only about 200C, but it should still work the same I think (tho there's a command line arg on the kiln-tuner to adjust it).

So, I'd definitely check the code version. It was about 10 days ago that fix was merged.

One other thing I spotted while doing this: it is possible to accidentally run multiple processes accessing the same kiln hardware at the same time, which "runs", but will cause lots of weird issues. @jbruce12000 I've just added a new MR which adds a really simple fcntl based lock to eliminate this possibility.

**Comment by murraycs** [comment] 2021-11-13 21:18
@felixn-unity you've got great help with software from the other folks, but so as not to overlook another possibility while in the weeds of code: could your SSR have failed?

**Comment by iog-creator** [comment] 2021-11-13 21:47
Humm possibly. I did test it with the heating coil and it worked. But it
may just not be capable of turning itself off. I think it's still the pi
gpio pin though not turning off and on. If I put a meter on the pins I
should see if it's switching on and off. That would tell me.

Bryon McCoy
203-989-0875

**Comment by jbruce12000** [comment] 2021-11-14 20:34
see this page. it can help you troubleshoot gpio pins. I thought I destroyed a pi once too. turned out I just did not have the breakout board plugged in properly. https://github.com/jbruce12000/kiln-controller/blob/master/docs/troubleshooting.md

**Comment by JoeyG1973** [comment] 2021-11-29 02:10
My Kiln is really old too.  Let me give you my setup.  There was a hole in the door that was a peep hole I guess back in the day.  I used that hole and the k probe goes in through the door and sticks out about an inch.  The door itself has coils on it.  There is still an old non powered analog temp gauge that has wires going into the side and I am assuming has the probe buried in the block somewhere.  I have similar but really weird zn results as @felixn-unity.
```
pid_kp = -302.23145277133233
pid_ki = 0.037194430278414264
pid_kd = 849.370624756990411
```

I think the issue is the location of the probe.  It is not centrally located in relation to the coils.  Thoughts?
[zn.csv](https://github.com/jbruce12000/kiln-controller/files/7615008/zn.csv)

**Comment by jbruce12000** [comment] 2022-02-10 18:16
wow. that's some crazy output. One thing is for sure @JoeyG1973 , your kiln heats very slowly. It took 4.5 minutes to go from 40 to 100. I'm assuming this if F.

I used the ZN auto-tuning on my kiln and it worked ok, but not perfect.

**Closed as completed** 2022-02-28 16:31 UTC
