### ISSUE TITLE
Schedule taking much longer than specified

### ISSUE THREAD

**Issue by sactheskydiver** [jbruce12000/kiln-controller#142] opened 2023-07-06 16:33 UTC
Using the premade cone 5 long bisque I started firing the 15 hour schedule approx 13 hours ago yet the time remaining is 10 hours rather than 2. Watching the count down timer I can definitely confirm the clock is counting down much slower than the actual passage of time.

**Comment by jbruce12000** [comment] 2023-07-06 16:49
wow. that's bad. can you post the log and config.py so I can check that out?

**Comment by jbruce12000** [comment] 2023-07-06 16:50
There are lots of possible causes for this. Most likely is that the temperature is constantly outside the window and the kiln is waiting to catch up.

**Comment by sactheskydiver** [comment] 2023-07-06 17:07
Where will I find the log? I'll post it asap 

I haven't done any calibration or tuning yet so being outside the window is extremely likely

**Comment by jbruce12000** [comment] 2023-07-06 17:27
see https://github.com/jbruce12000/kiln-controller/blob/master/docs/logs.md

that has instructions for how to zip up the log.

If you want the kiln to strictly follow time and never wait to catch up, set the following in config.py:

kiln_must_catch_up = False

This is NOT the default because most people want to heat as fast as possible during some part of their run.

**Comment by sactheskydiver** [comment] 2023-07-07 01:14
So I just went ahead and did the PID auto tune because of the ossilations I got in the previous test and checking the log it was very much due to being outside the window. 

It recommended these settings. 

Kp= -20.8 (a negative)
Ki= 10.2
Kd=1116

The P and D seem widely outside what the suggested starting point was. Is this likely a hardware issue?

**Comment by jbruce12000** [comment] 2023-07-07 12:22
haha. that's not right. Kp should always be positive. The higher the number the more impact it has. Ki should always be positive. The smaller the number, the larger the impact. Kd should always be positive. The larger the number, the higher the impact.

You can do manual tuning. This is an iterative process where you change one setting Kp,Ki or Kd and test then reflect. This is a pain and takes time, but you'll get close after a few tests. No tuning will be perfect at all temperatures... at low temps, it's ok for temps to swing a little as long as it settles. Check out the graphs here for a well tuned kiln...

https://github.com/jbruce12000/kiln-stats/blob/main/output/final.pdf

You can see temps swing at the start, but then settle to an average error of just a degree F. 

See this doc for manual tuning:

https://github.com/jbruce12000/kiln-controller/blob/master/docs/pid_tuning.md

Maybe @adq can suggest why the autotuner does not work in this case. It's likely related to the gpio output inversion you have.

**Comment by jbruce12000** [comment] 2023-07-07 17:40
since we know the cause of the issue and you're working on tuning [the fix], I'm gonna close this. open another issue if ya need.

**Closed by jbruce12000** 2023-07-07 17:40 UTC
